### ISSUE TITLE
How do I change ports?

### ISSUE THREAD

**Issue by Lippiece** [TeamPiped/Piped-Docker#38]
Hi. Thanks for your work. I would want something like #6. Run it locally and use my own global reverse-proxy to make it available from the outside. I would also like to change ports in the configuration since I have other service on the server that uses the required ports.

Any tips would be appreciated. I'm a small bit more advanced than a newbie.

**Comment by Bnyro** [comment]
You can use the `ports` option of docker compose.

First, run the `./configure-instance.sh` script as documented at docs.piped.video.

Then, add the following to pipedfrontend in the docker-compose.yml
```
ports:
    - "127.0.0.1:8888:8080"
```
so that it looks like
```
pipedfrontend:
  image: ...
  ports:
    - "127.0.0.1:8888:80"
piped-proxy:
...
```
where `8888` is the port that you want to use for the frontend in this example.

For the pipedbackend, you can do the same with
```
ports:
    - "127.0.0.1:8888:8080"
```
and for the piped-proxy with
For the pipedbackend, you can do the same with
```
ports:
    - "127.0.0.1:8888:8080"
```
(again, replace 8888 with the port that you want to use).
